### ISSUE TITLE
Feature request : Penalties after activation.

### ISSUE THREAD

**Issue by NoManColonies** [XeoNovaDan/Adrenaline#1]
Adrenaline is very cool at the same time very overpowered so for that matter I would like to suggest having penalties like Debuff ,Hunger drain, etc. after each rush. For example something like Hediff with 5 stages consist of Deadly, extreme, serious, minor and hidden.
How that work? lemme explains. So after the end of each rush Pawn/Creature will get Tired hediff which increase their tiredness ,hunger and lower their movement ,manipulation. Starting severities is based on adrenaline severities with each tick their severity slowly goes down to minor then hidden. while Pawn/Creature has already got tired effect if adrenaline rush goes again it will increase severity  at the end of rush by 2 of the currently having tired hediff i.e. pawn A has first rush then got tired at extreme severity then when it dropped to minor then unfortunately rush goes again which increase severity by 2 from minor to extreme regardless of adrenaline severity at the end of the recent rush. First rush will always cause hediff severity based on adrenaline severity(when pawn doesn't have Tired hediff on) but IF they have it will increase the severity of current one by 2 and during the rush tired hediff won't take effect until the end of current rush and IF pawn already has tired hediff at serious severity next rush will cause severity to goes deadly which has a chance to cause heart attack.(Pawn cannot get Tired hediff at deadly stage at the end of the rush unless they already got one at serious severity).

**Comment by XeoNovaDan** [comment]
Sorry I didn't see this sooner; GitHub doesn't exactly notify me and I'm not sure where abouts you can change that! Something along the lines has been added since, so I am going to close this. Thanks though :)
